### ISSUE TITLE
test code 에러

### ISSUE THREAD

**Issue by jwmoonP** [ClustProject/KETIPreDataIngestion#2]
테스트 코드 중 Version 2로 설정했을 경우 아래와 같은 코드에서 에러가 발생함

ms_list = DBClient.measurement_list(db_name)
print(ms_list)

**Comment by keymemory** [comment]
현재 InfluxDB 1.8.9 -> InfluxDB 2.0.9로 data를 전부 migration한 상태가 아니기 때문에
찾고자 하는 measurement의 database가 존재하지 않아서 생기는 문제입니다.
추후에 남은 database를 전부 migration 할 예정입니다.
